### ISSUE TITLE
Deserialization tests

### ISSUE THREAD

**Issue by drklee3** [KamranMackey/lastfm-rs#4]
I have some deserialization tests written locally when testing #3, which uses a downloaded json file of the endpoint data.

I'm just wondering what way of testing would be preferred, currently I just have local `.json` files, which I *think* follows Last.fm's ToS.  Quick skim through it seems like it's fine if it uses data from a user that gives permission and is below their "Reasonable Usage Cap" of 100 MB. 

> Any use, storage, publication, distribution, communication, making available or otherwise of Last.fm Data in excess of the Reasonable Usage Cap is strictly prohibited. The "Reasonable Usage Cap" is a maximum of 100 MB, as may be updated by Last.fm from time to time.

So the 2 options:

1. Use downloaded `.json` files saved in the repo, which would need to be updated if Last.fm updates their API.
2. Actually fetch data from the API during tests, though if CI tests are to be added it would require a Last.fm key provided as a workflow secret.  Users would also need to run `cargo test` with an api key and target user (as env vars likely).

**Comment by evieluvsrainbows** [comment]
Either option sounds good with me. We could go with option 1 for now; and then work on maybe implementing option 2 later, or we could go straight to option 2 if its more future proof to any changes to Last.fm's API. I'm okay with adding an API key to my workflow secrets, I'll create a special one just for that if necessary.
